#!/usr/bin/env bash
#
# Serve a white-label tenant's own domain.
#
# The branding service has always named this script as the operator step that
# takes a domain from DNS_VERIFIED to actually serving — see
# `verify_domain()` in backend/services/admin/services/branding_service.py.
# It was never written, so every tenant domain stopped at "DNS verified" and
# then fell through to the default vhost, which 301s to tuskaex.com. This is it.
#
# Usage:
#   ./deploy/scripts/connect-tenant-domain.sh <domain> [--app <sub>] [--admin <sub>]
#
#   apex mode       ./connect-tenant-domain.sh broker.com --admin admin
#                   → serves broker.com, www.broker.com, admin.broker.com
#   subdomain mode  ./connect-tenant-domain.sh broker.com --app app
#                   → serves app.broker.com only (apex left to the tenant)
#
# Removal:
#   ./deploy/scripts/connect-tenant-domain.sh <domain> --remove
#
# ── TLS: this REQUIRES the domain to be proxied through Cloudflare ────────
# The certificate below is TuskaEx's Cloudflare Origin cert. It covers
# tuskaex.com and *.tuskaex.com and CANNOT cover a customer's domain. It works
# only because Cloudflare terminates TLS for the visitor and re-encrypts to us
# in Full (not Full strict) mode, where our certificate is
# encrypted-but-unverified.
#
# So the tenant must:
#   1. add their domain to the platform's Cloudflare account,
#   2. point its nameservers there at their registrar,
#   3. keep the A records PROXIED (orange cloud) → the origin IP.
#
# Grey-cloud it, or point DNS straight at the origin, and browsers get a
# certificate-name mismatch. If you ever need to serve a tenant domain without
# Cloudflare, that is the certbot route and this script is not it.
set -euo pipefail

NGINX_AVAILABLE=/etc/nginx/sites-available
NGINX_ENABLED=/etc/nginx/sites-enabled
CERT=/etc/ssl/cloudflare/origin.pem
CERT_KEY=/etc/ssl/cloudflare/origin-key.pem

die() { echo "✗ $*" >&2; exit 1; }

DOMAIN="${1:-}"
[ -n "$DOMAIN" ] || die "Usage: $0 <domain> [--app <sub>] [--admin <sub>] [--remove]"
shift

# Apex only — the admin form enforces the same shape, and a value with a scheme
# or a path would silently produce a server_name nginx never matches.
echo "$DOMAIN" | grep -qE '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$' \
  || die "Not a bare domain: '$DOMAIN' (no https://, no www, no path)"

APP_SUB=""; ADMIN_SUB=""; REMOVE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --app)    APP_SUB="${2:-}"; shift 2 ;;
    --admin)  ADMIN_SUB="${2:-}"; shift 2 ;;
    --remove) REMOVE=1; shift ;;
    *) die "Unknown argument: $1" ;;
  esac
done

CONF_NAME="tenant-${DOMAIN}.conf"
CONF="$NGINX_AVAILABLE/$CONF_NAME"

if [ "$REMOVE" -eq 1 ]; then
  sudo rm -f "$NGINX_ENABLED/$CONF_NAME" "$CONF"
  sudo nginx -t
  sudo systemctl reload nginx
  echo "✓ $DOMAIN removed and nginx reloaded"
  exit 0
fi

[ -f "$CERT" ] || die "Origin certificate missing at $CERT"

# Which hostnames this tenant answers on. Mirrors hostnames_for() in
# branding_service.py — if these two ever disagree, DNS verifies green and the
# site still 404s, which is a miserable thing to debug.
if [ -n "$APP_SUB" ]; then
  TRADER_NAMES="${APP_SUB}.${DOMAIN}"
else
  TRADER_NAMES="${DOMAIN} www.${DOMAIN}"
fi

echo "▶ $DOMAIN"
echo "    trader: $TRADER_NAMES"
[ -n "$ADMIN_SUB" ] && echo "    admin:  ${ADMIN_SUB}.${DOMAIN}"

# nginx variable names allow only [A-Za-z0-9_], and every tenant file defines
# its own upgrade map — a shared name would be a duplicate-variable error the
# moment a second tenant is connected.
SLUG=$(echo "$DOMAIN" | tr '.-' '__')

TMP=$(mktemp)
cat > "$TMP" <<EOF
# ${DOMAIN} — white-label tenant. GENERATED by
# deploy/scripts/connect-tenant-domain.sh; re-run that rather than editing here.
#
# Cloudflare must front this domain: the certificate is TuskaEx's origin cert
# and cannot cover ${DOMAIN}. See the script header.

# Every proxy_set_header below sits at server level, because nginx's
# inheritance is all-or-nothing: one such directive inside a location discards
# the whole inherited set. A blanket "Connection: upgrade" on ordinary requests
# breaks keepalive, so it goes through this map.
map \$http_upgrade \$conn_upgrade_${SLUG} {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${TRADER_NAMES}$([ -n "$ADMIN_SUB" ] && echo " ${ADMIN_SUB}.${DOMAIN}");
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${TRADER_NAMES};

    ssl_certificate     ${CERT};
    ssl_certificate_key ${CERT_KEY};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Frame-Options "SAMEORIGIN" always;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
    gzip_min_length 256;

    client_max_body_size 15M;
    limit_req zone=web_limit burst=40 nodelay;

    # Cloudflare real-IP mapping is already applied at http level from
    # /etc/nginx/conf.d/, so it is NOT included here: a missing include file is
    # a hard nginx error, and this file must never be the reason a reload fails.

    # Host is forwarded verbatim on purpose. The app reads it to decide which
    # tenant's branding to serve, and the gateway reads it (via X-Forwarded-Host
    # from the Next API proxy) to scope the auth cookie's Domain. Hard-code it
    # and every tenant would get TuskaEx's chrome and a cookie for the wrong
    # domain.
    proxy_http_version 1.1;
    proxy_set_header Host              \$host;
    proxy_set_header X-Real-IP         \$remote_addr;
    proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Upgrade           \$http_upgrade;
    proxy_set_header Connection        \$conn_upgrade_${SLUG};

    # Same-origin sockets. A tenant's cookie is scoped to its own domain and is
    # never sent to api.tuskaex.com, so /ws/trades would close 4003 there and
    # the terminal would silently stop receiving fills.
    location /ws/ {
        proxy_pass http://gateway_api;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
        proxy_buffering off;
    }

    location /_next/static/ {
        proxy_pass http://trader_frontend;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location /charting_library/ {
        proxy_pass http://trader_frontend;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        proxy_pass http://trader_frontend;
        proxy_read_timeout 86400;
        proxy_buffering off;
    }
}
EOF

if [ -n "$ADMIN_SUB" ]; then
cat >> "$TMP" <<EOF

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${ADMIN_SUB}.${DOMAIN};

    ssl_certificate     ${CERT};
    ssl_certificate_key ${CERT_KEY};
    ssl_protocols       TLSv1.2 TLSv1.3;

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Frame-Options "SAMEORIGIN" always;

    client_max_body_size 15M;

    proxy_http_version 1.1;
    proxy_set_header Host              \$host;
    proxy_set_header X-Real-IP         \$remote_addr;
    proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Upgrade           \$http_upgrade;
    proxy_set_header Connection        \$conn_upgrade_${SLUG};

    location /_next/static/ {
        proxy_pass http://admin_frontend;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        proxy_pass http://admin_frontend;
        proxy_read_timeout 300;
    }
}
EOF
fi

sudo cp "$TMP" "$CONF"
rm -f "$TMP"
sudo ln -sf "$CONF" "$NGINX_ENABLED/$CONF_NAME"

# Validate BEFORE reloading. A bad generated file would otherwise take every
# site on this box down, not just the tenant's.
if ! sudo nginx -t; then
  sudo rm -f "$NGINX_ENABLED/$CONF_NAME"
  die "nginx rejected the generated config; the tenant vhost was NOT enabled (everything else untouched)"
fi
sudo systemctl reload nginx

echo "✓ $DOMAIN is being served."
echo "  Next: confirm the domain is PROXIED (orange cloud) in Cloudflare, then"
echo "  mark it provisioned in the admin panel so its status reaches READY."
