"""Phase 4: Staking — plans, positions, daily reward accruals.

Models per STAKING_PAGE.docx:
  staking_plans            — catalogue (Flexible, Locked-1Y, Locked-2Y, Locked-3Y)
  staking_positions        — a user's stake in a plan
  staking_reward_accruals  — daily reward rows generated by the scheduler

APYs come from XP_Reward_mechanism slide 14 (1Y=12%, 2Y=18%, 3Y=24%) and the
plan adds a "Flexible" mode at 6% with no lock-in. Trading-bonus multiplier is
100% (10000 bps) for locked plans, 0 for flexible.

Revision ID: 0022
Revises: 0021
"""
import sqlalchemy as sa
from alembic import op


revision = "0022"
down_revision = "0021"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS staking_plans (
            id                            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            slug                          VARCHAR(60) UNIQUE NOT NULL,
            label                         VARCHAR(80) NOT NULL,
            description                   TEXT,
            mode                          VARCHAR(10) NOT NULL CHECK (mode IN ('flexible','locked')),
            lock_months                   INTEGER,
            apy_bps                       INTEGER NOT NULL CHECK (apy_bps >= 0),
            min_amount                    NUMERIC(18,2) NOT NULL DEFAULT 0,
            trading_bonus_multiplier_bps  INTEGER NOT NULL DEFAULT 0,
            display_order                 INTEGER NOT NULL DEFAULT 0,
            is_active                     BOOLEAN NOT NULL DEFAULT TRUE,
            CONSTRAINT staking_plans_lock_consistency
              CHECK ( (mode = 'flexible' AND lock_months IS NULL)
                   OR (mode = 'locked'   AND lock_months IS NOT NULL AND lock_months > 0) )
        );
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS staking_positions (
            id                       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            user_id                  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            plan_id                  UUID NOT NULL REFERENCES staking_plans(id),
            principal                NUMERIC(18,2) NOT NULL,
            started_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
            unlocks_at               TIMESTAMPTZ,
            state                    VARCHAR(20) NOT NULL DEFAULT 'active'
                                       CHECK (state IN ('active','withdrawn','early_exit')),
            trading_bonus_active     BOOLEAN NOT NULL DEFAULT FALSE,
            trading_bonus_credited   NUMERIC(18,2) NOT NULL DEFAULT 0,
            last_accrued_at          TIMESTAMPTZ,
            ended_at                 TIMESTAMPTZ
        );
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_staking_positions_user_state ON staking_positions(user_id, state);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_staking_positions_active ON staking_positions(state) WHERE state = 'active';")

    op.execute("""
        CREATE TABLE IF NOT EXISTS staking_reward_accruals (
            id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            position_id   UUID NOT NULL REFERENCES staking_positions(id) ON DELETE CASCADE,
            period_start  TIMESTAMPTZ NOT NULL,
            period_end    TIMESTAMPTZ NOT NULL,
            reward_amount NUMERIC(18,2) NOT NULL,
            paid_at       TIMESTAMPTZ
        );
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_staking_accruals_position_paid ON staking_reward_accruals(position_id, paid_at);")
    # Prevent the cron from inserting two rows for the same period if it
    # accidentally fires twice in quick succession.
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS ux_staking_accruals_period
            ON staking_reward_accruals(position_id, period_start, period_end);
    """)

    # Seed plans
    seeds = [
        # slug,        label,        mode,       lock_months, apy_bps, min_amount, bonus_bps, order
        ("flexible",   "Flexible",   "flexible", None,         600,      10,           0,    1),
        ("locked_1y",  "Locked 1 Year", "locked",   12,        1200,    100,       10000,    2),
        ("locked_2y",  "Locked 2 Year", "locked",   24,        1800,    100,       10000,    3),
        ("locked_3y",  "Locked 3 Year", "locked",   36,        2400,    100,       10000,    4),
    ]
    descriptions = {
        "flexible":  "Provide liquidity with no lock-in. Withdraw anytime. Lower reward rate.",
        "locked_1y": "Lock for 12 months for a higher reward rate plus a 1× trading bonus.",
        "locked_2y": "Lock for 24 months for an enhanced reward structure plus a 1× trading bonus.",
        "locked_3y": "Lock for 36 months for the maximum reward rate plus a 1× trading bonus.",
    }
    stmt = sa.text("""
        INSERT INTO staking_plans
          (slug, label, description, mode, lock_months, apy_bps, min_amount,
           trading_bonus_multiplier_bps, display_order)
        VALUES
          (:slug, :label, :description, :mode, :lock_months, :apy_bps, :min_amount,
           :trading_bonus_multiplier_bps, :display_order)
        ON CONFLICT (slug) DO NOTHING
    """)
    bind = op.get_bind()
    for s in seeds:
        bind.execute(stmt, dict(
            slug=s[0], label=s[1], description=descriptions[s[0]],
            mode=s[2], lock_months=s[3], apy_bps=s[4], min_amount=s[5],
            trading_bonus_multiplier_bps=s[6], display_order=s[7],
        ))


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS staking_reward_accruals;")
    op.execute("DROP TABLE IF EXISTS staking_positions;")
    op.execute("DROP TABLE IF EXISTS staking_plans;")
